# Site settings
course_name: Deep Learning for Data Science (DL4DS)
course_description: "In this course students will gain an understanding of the fundamentals in Deep Learning and then apply those concepts in exercises and applications in python. You'll learn the foundations of training and inference, then become familiar with canonical network architectures including convolutional neural networks and transformers. We'll look at generative pre- trained Transformer models and pros and cons of prompt engineering versus finetuning. Finally, students will be able to apply many of the techniques they learned in a final class project."
course_semester: "Spring 2024"

baseurl: "/sp2024" # the subpath of your site, e.g. /blog/
url: "http://dl4ds.github.io" # the base hostname & protocol for your site

schoolname: "Boston University Faculty for Computing and Data Science"
schoolurl: "https://www.bu.edu/cds-faculty/"
twitter_username: trgardos 
google_scholar_id: tY3MyCgAAAAJ
linkedin_username: thomas-gardos

address: |
    665 Commonwealth Avenue
    Boston, MA 02215
    USA

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X
google_analytics: G-J2ZBMYKFT8

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
