# Site settings
course_name: Deep Learning for Data Science (DL4DS)
course_description: "In this course we will dive into Deep Learning. We'll balance important theoretical concepts with hands on network training and applications using modern deep learning python frameworks. We'll explore numerous network architectures like CNNs, transformers, and the rapidly developing state-of-the-art of large pre-trained foundation models. You'll have the chance to apply what you've learned in multiple projects."
course_semester: "Fall 2025"

baseurl: "/fa2025" # the subpath of your site, e.g. /blog/
url: "http://dl4ds.github.io" # the base hostname & protocol for your site

schoolname: "Boston University Faculty for Computing and Data Science"
schoolurl: "https://www.bu.edu/cds-faculty/"
twitter_username: jconsidi
# google_scholar_id: tY3MyCgAAAAJ
linkedin_username: jconsidi
github_repo: https://github.com/DL4DS/fa2025

address: |
    Boston, MA
    USA

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X
#google_analytics: G-J2ZBMYKFT8

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    discussions:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
